# 数据操作

In [1]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过张量的shape属性访问张量的形状和张量中元素的总数，numel函数获取张量中元素的总数

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

reshape函数能够改变张量的形状而不改变元素数值和元素值

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、其他常量或者特定分布中随机采样的数字

In [ ]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值

In [15]:
list1 = [[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]]
torch.tensor(list1)

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [16]:
torch.tensor(list1).shape

torch.Size([1, 3, 4])

常见的标准算术运算符（+、-、*、/和**），都可以被升级为按元素运算

In [18]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  #**是求幂运算符

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素方式应用更多的计算

In [19]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

把多个张量连结在一起，dim表示在第几维度进行合并（即第几层中括号）

In [ ]:
X = torch.arange(12, dtype = torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim = 0), torch.cat((X, Y), dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元张量

In [21]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和会产生一个只有一个元素的张量

In [22]:
X.sum()

tensor(66.)

即使形状不同，我们仍然可以通过调用广播机制（broadcasting mechanism）来执行按元素操作

In [23]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [24]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素，感觉使用方法很类似numpy

In [25]:
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除了读取外，我们还可以通过指定索引来将元素写入矩阵

In [26]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值相同的值，我们只需要索引所有的元素，然后为它们赋值

In [29]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 10., 11.]])

运行一些操作可能会导致为新结果分配内存
下面就是给Y开辟了新的内存空间
如果数据量很大，会占用很大内存

In [30]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作（视频给的例子），我理解创建了新的Z也会重新分配内存呀，这应该不对

In [31]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 123239414017760
id(Z): 123239414017760


执行原地操作（看弹幕），执行+=操作可以实现原地操作，不开辟新的内存空间
后面视频给了相同的+=操作，如果不需要重复使用Y，可以Y[:] = X + Y 或者 Y += X

In [33]:
before_id_from_danmu = id(Y)
Y += X
id(Y) == before_id_from_danmu

True

转换为numpy张量

In [34]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python标量

In [35]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)